# Generated by Django 6.0.6 on 2026-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='dashboard_n_audienc_c55551_idx',
            old_name='dashboard_n_audienc_3f2a1c_idx',
        ),
    ]
