# Generated by Django 6.0.6 on 2026-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_account_ddc8cc_idx',
            old_name='accounts_ac_account_2b5d9c_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_status_07de41_idx',
            old_name='accounts_ac_status_9f1a7d_idx',
        ),
    ]
