# Generated by Django 6.0.6 on 2026-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_referen_923a88_idx',
            old_name='transaction_referen_5c7a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_txn_typ_451b15_idx',
            old_name='transaction_txn_typ_2d8e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_status_71abbb_idx',
            old_name='transaction_status_7a3c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_created_67ce7b_idx',
            old_name='transaction_created_1b6d2a_idx',
        ),
    ]
