# Generated by Django 6.0.6 on 2026-07-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_referen_8cc656_idx',
            old_name='loans_loan_referen_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_status_962e99_idx',
            old_name='loans_loan_status_d4e5f6_idx',
        ),
    ]
